name: surveychimp
region: ams
services:
- build_command: npx nx run surveychimp-api:build:production
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: jonatanhallenberg/surveychimp
  http_port: 3333
  instance_count: 1
  instance_size_slug: basic-xxs
  name: surveychimp-api
  routes:
  - path: /
  run_command: node ./dist/apps/surveychimp-api/main.js
  source_dir: /