@baseUrl=https://surveychimp-test-rhsvk.ondigitalocean.app

POST {{baseUrl}}/survey
Content-Type: application/json

{
    "recipient": {
        "name": "Jonatan",
        "mobileNumber": "070 123 12 12"
    }
}

###

GET {{baseUrl}}/survey/635becbbfd734262f1059b20

###

PATCH {{baseUrl}}/survey/635ad5b2cf3d50daaa87c966
Content-Type: application/json

{
    "rating": 3,
    "comment": "Det var toppen!"
}